export const cityList = [
  { value: '01', label: 'Ha Noi' },
  { value: '02', label: 'Ha Giang' },
  { value: '04', label: 'Cao Bang' },
  { value: '06', label: 'Bac Kan' },
  { value: '08', label: 'Tuyen Quang' },
  { value: '10', label: 'Lao Cai' },
  { value: '11', label: 'Dien Bien' },
  { value: '12', label: 'Lai Chau' },
  { value: '14', label: 'Son La' },
  { value: '15', label: 'Yen Bai' },
  { value: '17', label: 'Hoa Binh' },
  { value: '19', label: 'Thai Nguyen' },
  { value: '20', label: 'Lang Son' },
  { value: '22', label: 'Quang Ninh' },
  { value: '24', label: 'Bac Giang' },
  { value: '25', label: 'Phu Tho' },
  { value: '26', label: 'Vinh Phuc' },
  { value: '27', label: 'Bac Ninh' },
  { value: '30', label: 'Hai Duong' },
  { value: '31', label: 'Hai Phong' },
  { value: '33', label: 'Hung Yen' },
  { value: '34', label: 'Thai Binh' },
  { value: '35', label: 'Ha Nam' },
  { value: '36', label: 'Nam Dinh' },
  { value: '37', label: 'Ninh Binh' },

  { value: '38', label: 'Thanh Hoa' },
  { value: '40', label: 'Nghe An' },
  { value: '42', label: 'Ha Tinh' },
  { value: '44', label: 'Quang Binh' },
  { value: '45', label: 'Quang Tri' },
  { value: '46', label: 'Thua Thien Hue' },
  { value: '48', label: 'Da Nang' },
  { value: '49', label: 'Quang Nam' },
  { value: '51', label: 'Quang Ngai' },
  { value: '52', label: 'Binh Dinh' },
  { value: '54', label: 'Phu Yen' },
  { value: '56', label: 'Khanh Hoa' },
  { value: '58', label: 'Ninh Thuan' },
  { value: '60', label: 'Binh Thuan' },
  { value: '62', label: 'Kon Tum' },
  { value: '64', label: 'Gia Lai' },
  { value: '66', label: 'Dak Lak' },
  { value: '67', label: 'Dak Nong' },
  { value: '68', label: 'Lam Dong' },

  { value: '70', label: 'Binh Phuoc' },
  { value: '72', label: 'Tay Ninh' },
  { value: '74', label: 'Binh Duong' },
  { value: '75', label: 'Dong Nai' },
  { value: '77', label: 'Ba Ria - Vung Tau' },
  { value: '79', label: 'Ho Chi Minh' },
  { value: '80', label: 'Long An' },
  { value: '82', label: 'Tien Giang' },
  { value: '83', label: 'Ben Tre' },
  { value: '84', label: 'Tra Vinh' },
  { value: '86', label: 'Vinh Long' },
  { value: '87', label: 'Dong Thap' },
  { value: '89', label: 'An Giang' },
  { value: '91', label: 'Kien Giang' },
  { value: '92', label: 'Can Tho' },
  { value: '93', label: 'Hau Giang' },
  { value: '94', label: 'Soc Trang' },
  { value: '95', label: 'Bac Lieu' },
  { value: '96', label: 'Ca Mau' },
];
